// =============================================================================
// test_gen_world.cpp — verifies that scene.json actually drives the generated
// Webots scene.
//
// Two layers:
//  1. Static — the shipped scene.json's values must appear in the generated
//     .proto/.wbt, the connector geometry must be physically able to bond, and
//     the module layout must match the trace.
//  2. Variant — regenerate from a DIFFERENT config into temporary paths and
//     confirm the outputs follow it. This is what proves the pipeline is
//     config-driven rather than emitting constants that merely look right.
//
// Assumes tools/gen_world.exe has been built (build_and_test.sh runs it first).
// =============================================================================

#include "../controllers/catom3d_controller/catom3d_core.hpp"
#include "../controllers/catom3d_controller/scene_config.hpp"

#include <iostream>
#include <iomanip>
#include <sstream>
#include <cmath>
#include <cstdlib>
#include <set>
#include <tuple>

static int g_fail = 0, g_pass = 0;

static void check(bool cond, const std::string& what) {
    if (cond) ++g_pass;
    else { ++g_fail; std::cout << "  FAIL: " << what << "\n"; }
}
static void checkNear(double got, double want, double tol, const std::string& what) {
    bool ok = std::fabs(got - want) <= tol;
    if (!ok) std::cout << "  (got " << std::setprecision(10) << got
                       << ", want " << want << ")\n";
    check(ok, what);
}

static std::string slurp(const std::string& path) {
    std::ifstream f(path.c_str());
    if (!f.is_open()) return "";
    std::ostringstream ss; ss << f.rdbuf(); return ss.str();
}

// First number following `token` in `text`; NaN when the token is absent.
// Occurrences not actually followed by a number are skipped, so prose in the
// generated comments ("... m radius.", "tensileStrength/shearStrength") cannot
// shadow the real field.
static double numAfter(const std::string& text, const std::string& token) {
    for (size_t p = text.find(token); p != std::string::npos;
         p = text.find(token, p + token.size())) {
        size_t q = p + token.size();
        while (q < text.size() && (text[q]==' '||text[q]=='\t'||text[q]=='['||text[q]=='"')) ++q;
        if (q < text.size() &&
            ((text[q] >= '0' && text[q] <= '9') || text[q] == '-' || text[q] == '+'))
            return std::strtod(text.c_str() + q, nullptr);
    }
    return std::nan("");
}

// std::system goes through cmd.exe on Windows, which does not accept "./path".
static int runTool(const std::string& args) {
    return std::system(("tools\\gen_world.exe " + args).c_str());
}
static bool contains(const std::string& hay, const std::string& needle) {
    return hay.find(needle) != std::string::npos;
}
static int countOf(const std::string& hay, const std::string& needle) {
    int n = 0;
    for (size_t p = hay.find(needle); p != std::string::npos; p = hay.find(needle, p + needle.size())) ++n;
    return n;
}

// Pull the translation/rotation of each named Connector out of the PROTO text.
struct ConnectorRec { bool found = false; double t[3] = {0,0,0}, r[4] = {0,0,0,0}; };
static ConnectorRec readConnector(const std::string& proto, int idx) {
    ConnectorRec rec;
    std::ostringstream nameTok; nameTok << "name \"con" << idx << "\"";
    size_t np = proto.find(nameTok.str());
    if (np == std::string::npos) return rec;
    size_t blockStart = proto.rfind("Connector {", np);
    if (blockStart == std::string::npos) return rec;
    std::string block = proto.substr(blockStart, np - blockStart);
    size_t tp = block.find("translation ");
    size_t rp = block.find("rotation ");
    if (tp == std::string::npos || rp == std::string::npos) return rec;
    std::istringstream ts(block.substr(tp + 12));  ts >> rec.t[0] >> rec.t[1] >> rec.t[2];
    std::istringstream rs(block.substr(rp + 9));   rs >> rec.r[0] >> rec.r[1] >> rec.r[2] >> rec.r[3];
    rec.found = true;
    return rec;
}

// Rodrigues: rotate v by `angle` about unit `axis`.
static void rotateVec(const double axis[3], double angle, const double v[3], double out[3]) {
    double c = std::cos(angle), s = std::sin(angle);
    double dot = axis[0]*v[0] + axis[1]*v[1] + axis[2]*v[2];
    double cx[3] = { axis[1]*v[2] - axis[2]*v[1],
                     axis[2]*v[0] - axis[0]*v[2],
                     axis[0]*v[1] - axis[1]*v[0] };
    for (int i = 0; i < 3; ++i) out[i] = v[i]*c + cx[i]*s + axis[i]*dot*(1-c);
}

int main() {
    buildMotionLinks();

    // ================================================================ 1 ====
    // The shipped configuration, as generated by build_and_test.sh.
    SceneConfig cfg;
    std::string cfgPath = findSceneConfigPath();
    check(!cfgPath.empty(), "scene.json found");
    SceneConfigLoad load = loadSceneConfig(cfgPath, cfg);
    check(load.ok, "scene.json loads: " + load.error);

    std::string proto = slurp(cfg.outProto);
    std::string world = slurp(cfg.outWorld);
    check(!proto.empty(), "generated proto exists: " + cfg.outProto);
    check(!world.empty(), "generated world exists: " + cfg.outWorld);
    if (proto.empty() || world.empty()) {
        std::cout << "test_gen_world: cannot continue without generated files\n";
        return 1;
    }

    check(contains(proto, "GENERATED FILE"), "proto marked generated");
    check(contains(world, "GENERATED FILE"), "world marked generated");

    // ---- world-level physics from JSON ----
    checkNear(numAfter(world, "basicTimeStep"), cfg.basicTimeStep, 1e-9, "wbt basicTimeStep");
    // WorldInfo.gravity is an SFFloat (magnitude along the down axis). Emitting
    // a vector here makes Webots reject the world, so pin the shape exactly.
    {
        size_t gp = world.find("gravity ");
        check(gp != std::string::npos, "wbt has gravity");
        std::string line = world.substr(gp, world.find('\n', gp) - gp);
        double a = 0, b = 0;
        std::istringstream gs(line.substr(8));
        gs >> a;
        check(!(gs >> b), "gravity is a single scalar, not a vector");
        checkNear(a, cfg.gravity, 1e-9, "wbt gravity magnitude");
    }
    checkNear(numAfter(world, "CFM "), cfg.worldCFM, 1e-12, "wbt world CFM");
    checkNear(numAfter(world, "ERP "), cfg.worldERP, 1e-9,  "wbt world ERP");
    checkNear(numAfter(world, "physicsDisableTime"), cfg.physicsDisableTime, 1e-9,
              "wbt physicsDisableTime");
    checkNear(numAfter(world, "physicsDisableLinearThreshold"),
              cfg.physicsDisableLinearThreshold, 1e-9, "wbt physicsDisableLinearThreshold");
    checkNear(numAfter(world, "physicsDisableAngularThreshold"),
              cfg.physicsDisableAngularThreshold, 1e-9, "wbt physicsDisableAngularThreshold");

    // ---- contact properties (absent before this work: Webots' bounce 0.5
    //      default is what made resting modules jitter) ----
    check(countOf(world, "ContactProperties {") == 2, "two ContactProperties (catom-catom, catom-floor)");
    checkNear(numAfter(world, "coulombFriction"), cfg.coulombFriction, 1e-9, "wbt coulombFriction");
    checkNear(numAfter(world, "bounce "),         cfg.bounce,          1e-9, "wbt bounce");
    checkNear(numAfter(world, "bounceVelocity"),  cfg.bounceVelocity,  1e-9, "wbt bounceVelocity");
    checkNear(numAfter(world, "softCFM"),         cfg.softCFM,         1e-12,"wbt softCFM");
    checkNear(numAfter(world, "softERP"),         cfg.softERP,         1e-9, "wbt softERP");
    checkNear(numAfter(world, "rollingFriction"),    cfg.rollingFriction,    1e-9, "wbt rollingFriction");
    checkNear(numAfter(world, "forceDependentSlip"), cfg.forceDependentSlip, 1e-9, "wbt forceDependentSlip");
    checkNear(numAfter(world, "maxContactJoints"),   cfg.maxContactJoints,   1e-9, "wbt maxContactJoints");
    // rollingFriction is an SFVec3f: three components or Webots rejects it.
    {
        size_t rp = world.find("rollingFriction ");
        std::string line = world.substr(rp, world.find('\n', rp) - rp);
        double a=0,b=0,c=0,d=0;
        std::istringstream rs(line.substr(16));
        check(bool(rs >> a >> b >> c), "rollingFriction has three components");
        check(!(rs >> d), "rollingFriction has exactly three components");
    }
    check(contains(world, "material1 \"" + cfg.moduleMaterial + "\""), "module contact material");
    check(contains(world, "material2 \"" + cfg.floorMaterial + "\""),  "floor contact material");

    // ---- module physics from JSON ----
    checkNear(numAfter(proto, "radius"), cfg.boundingRadius, 1e-9, "proto boundingObject radius");
    checkNear(numAfter(proto, "linear"),  cfg.linearDamping,  1e-9, "proto linear damping");
    checkNear(numAfter(proto, "angular"), cfg.angularDamping, 1e-9, "proto angular damping");
    check(contains(proto, "physics Physics {"), "proto has Physics node");
    check(contains(proto, "mass IS mass"),      "proto mass is exposed as a field");
    check(contains(proto, "contactMaterial \"" + cfg.moduleMaterial + "\""), "proto contactMaterial");

    // ---- bonds ----
    check(countOf(proto, "Connector {") == 12, "12 connectors per module");
    check(countOf(proto, "tensileStrength " + std::string(cfg.tensileStrength == 15.0 ? "15" : "")) == 12
          || countOf(proto, "tensileStrength") == 12, "every connector has tensileStrength");
    checkNear(numAfter(proto, "tensileStrength"), cfg.tensileStrength, 1e-9, "connector tensileStrength");
    checkNear(numAfter(proto, "shearStrength"),   cfg.shearStrength,   1e-9, "connector shearStrength");
    checkNear(numAfter(proto, "distanceTolerance"), cfg.distanceTolerance, 1e-9, "connector distanceTolerance");
    checkNear(numAfter(proto, "axisTolerance"),     cfg.axisTolerance,     1e-9, "connector axisTolerance");
    checkNear(numAfter(proto, "rotationTolerance"), cfg.rotationTolerance, 1e-9, "connector rotationTolerance");
    check(countOf(proto, "type \"symmetric\"") == 12, "connectors are symmetric");
    // Lock state must stay under controller control, or a rolling module gets
    // grabbed by the modules it passes.
    check(countOf(proto, "autoLock FALSE") == 12,       "autoLock off on every connector");
    check(countOf(proto, "unilateralLock FALSE") == 12, "unilateralLock off on every connector");
    check(countOf(proto, "snap FALSE") == 12,           "snap off (would fight the Supervisor)");
    check(countOf(proto, "isLocked TRUE") == 12,        "bonded at world load, before controllers run");

    // ---- connector geometry: on the surface, aimed at the neighbour cell ----
    for (int i = 0; i < 12; ++i) {
        ConnectorRec c = readConnector(proto, i);
        std::ostringstream tag; tag << "con" << i;
        check(c.found, tag.str() + " present");
        if (!c.found) continue;

        // Sits on the module surface.
        double len = std::sqrt(c.t[0]*c.t[0] + c.t[1]*c.t[1] + c.t[2]*c.t[2]);
        checkNear(len, cfg.boundingRadius, 1e-6, tag.str() + " sits on the surface");

        // Points along its FCC connector direction.
        for (int k = 0; k < 3; ++k)
            checkNear(c.t[k], CONNECTOR_POS[i][k] * cfg.boundingRadius, 1e-6,
                      tag.str() + " translation matches CONNECTOR_POS");

        // The rotation must carry Webots' connector axis (+z) onto that direction.
        double zAxis[3] = {0,0,1}, mapped[3];
        double axis[3] = {c.r[0], c.r[1], c.r[2]};
        double alen = std::sqrt(axis[0]*axis[0] + axis[1]*axis[1] + axis[2]*axis[2]);
        if (alen > 1e-12) { axis[0]/=alen; axis[1]/=alen; axis[2]/=alen; }
        rotateVec(axis, c.r[3], zAxis, mapped);
        for (int k = 0; k < 3; ++k)
            checkNear(mapped[k], CONNECTOR_POS[i][k], 1e-6,
                      tag.str() + " +z axis aims at the neighbour cell");
    }

    // Opposite connectors must be antiparallel, or facing modules can never dock.
    for (int i = 0; i < 12; ++i)
        for (int k = 0; k < 3; ++k)
            checkNear(CONNECTOR_POS[i][k], -CONNECTOR_POS[(i+6)%12][k], 1e-12,
                      "connector directions come in opposite pairs");

    // ---- end-to-end: two adjacent modules present coincident connectors ----
    {
        GridPos a = {5,0,2};
        GridPos b = fccNeighbor(a, 0);                 // +x neighbour
        double aw[3], bw[3];
        gridToWorld(a, aw); gridToWorld(b, bw);
        ConnectorRec ca = readConnector(proto, 0);     // a's connector toward b
        ConnectorRec cb = readConnector(proto, 6);     // b's connector toward a
        double pa[3], pb[3];
        for (int k = 0; k < 3; ++k) { pa[k] = aw[k] + ca.t[k]; pb[k] = bw[k] + cb.t[k]; }
        double d = std::sqrt((pa[0]-pb[0])*(pa[0]-pb[0]) +
                             (pa[1]-pb[1])*(pa[1]-pb[1]) +
                             (pa[2]-pb[2])*(pa[2]-pb[2]));
        checkNear(d, 0.0, 1e-6, "adjacent modules' connectors coincide (bond can form)");
        check(d < cfg.distanceTolerance, "coincidence is inside distanceTolerance");
    }

    // ---- layout comes from the trace, not from hardcoded positions ----
    {
        std::vector<Move> moves = loadTraceFrom("controllers/catom3d_controller/trace.csv", nullptr);
        check(!moves.empty(), "trace loads for layout check");
        std::set<std::tuple<int,int,int>> inits;
        double zlo = 1e9;
        for (size_t i = 0; i < moves.size(); ++i) {
            inits.insert(std::make_tuple(moves[i].init.x, moves[i].init.y, moves[i].init.z));
            double w[3]; gridToWorld(moves[i].init, w); zlo = std::min(zlo, w[2]);
            gridToWorld(moves[i].to, w);                zlo = std::min(zlo, w[2]);
        }
        check(countOf(world, cfg.protoName + " {") == (int)inits.size(),
              "one node per module in the trace");
        check(contains(world, "name \"" + cfg.analystName + "\""), "analyst module exists in world");

        // Every module sits exactly on its lattice cell.
        int placed = 0;
        for (std::set<std::tuple<int,int,int>>::iterator it = inits.begin(); it != inits.end(); ++it) {
            GridPos g = {std::get<0>(*it), std::get<1>(*it), std::get<2>(*it)};
            double w[3]; gridToWorld(g, w);
            std::ostringstream want;
            want << std::setprecision(9) << "translation " << w[0] << " " << w[1] << " " << w[2];
            if (contains(world, want.str())) ++placed;
        }
        check(placed == (int)inits.size(), "every module is at its exact lattice position");

        // Floor sits directly under the lowest layer.
        size_t fp = world.find("name \"floor\"");
        check(fp != std::string::npos, "floor present");
        size_t solid = world.rfind("Solid {", fp);
        std::string floorBlock = world.substr(solid, fp - solid);
        double ft[3]; std::istringstream fs(floorBlock.substr(floorBlock.find("translation ") + 12));
        fs >> ft[0] >> ft[1] >> ft[2];
        double topZ = ft[2] + cfg.floorThickness / 2.0;
        checkNear(topZ, zlo - cfg.boundingRadius, 1e-6, "floor top touches the lowest module");
        check(contains(floorBlock, "contactMaterial \"" + cfg.floorMaterial + "\"") ||
              contains(world.substr(solid, 700), "contactMaterial \"" + cfg.floorMaterial + "\""),
              "floor uses its contact material");
    }

    // ================================================================ 2 ====
    // Variant config -> the outputs must follow it.
    {
        const char* variantPath = "tools/.build/variant_scene.json";
        {
            std::ofstream v(variantPath);
            check(v.is_open(), "can write variant config");
            v << "{\n"
                 "  \"world\": { \"basicTimeStep\": 4, \"gravity\": [0, 0, -1.62] },\n"
                 "  \"module\": { \"mass\": 0.42, \"boundingRadius\": 0.07,\n"
                 "                \"linearDamping\": 0.55, \"angularDamping\": 0.66 },\n"
                 "  \"contact\": { \"coulombFriction\": 0.25, \"bounce\": 0.4 },\n"
                 "  \"bonds\": { \"tensileStrength\": 99.0, \"shearStrength\": 88.0 },\n"
                 "  \"floor\": { \"margin\": 0.5 },\n"
                 "  \"output\": { \"proto\": \"tools/.build/VariantCatom.proto\",\n"
                 "                \"world\": \"tools/.build/variant_world.wbt\",\n"
                 "                \"protoName\": \"VariantCatom\" }\n"
                 "}\n";
        }
        int rc = runTool("tools/.build/variant_scene.json > tools/.build/variant.log 2>&1");
        check(rc == 0, "gen_world succeeds on the variant config");

        std::string vproto = slurp("tools/.build/VariantCatom.proto");
        std::string vworld = slurp("tools/.build/variant_world.wbt");
        check(!vproto.empty() && !vworld.empty(), "variant outputs written");
        if (!vproto.empty() && !vworld.empty()) {
            checkNear(numAfter(vworld, "basicTimeStep"), 4.0,  1e-9, "variant timestep applied");
            checkNear(numAfter(vproto, "radius"),        0.07, 1e-9, "variant radius applied");
            checkNear(numAfter(vproto, "linear"),        0.55, 1e-9, "variant linear damping applied");
            checkNear(numAfter(vproto, "angular"),       0.66, 1e-9, "variant angular damping applied");
            checkNear(numAfter(vworld, "coulombFriction"),0.25,1e-9, "variant friction applied");
            checkNear(numAfter(vworld, "bounce "),       0.4,  1e-9, "variant bounce applied");
            checkNear(numAfter(vproto, "tensileStrength"),99.0,1e-9, "variant tensile applied");
            checkNear(numAfter(vproto, "shearStrength"), 88.0, 1e-9, "variant shear applied");
            check(contains(vworld, "VariantCatom {"), "variant proto name used in world");
            check(countOf(vworld, "VariantCatom {") == 20, "variant world still has 20 modules");

            // Radius change must move the connectors with it.
            ConnectorRec vc = readConnector(vproto, 0);
            checkNear(vc.t[0], 0.07, 1e-6, "variant connector follows the new radius");

            // Floor must re-fit: bigger margin AND a lower top (bigger radius).
            double baseTop = numAfter(world,  "size ");    // touch to keep both used
            (void)baseTop;
            size_t fp = vworld.find("name \"floor\"");
            check(fp != std::string::npos, "variant floor present");
            size_t solid = vworld.rfind("Solid {", fp);
            std::string fb = vworld.substr(solid, fp - solid);
            double ft[3]; std::istringstream fs(fb.substr(fb.find("translation ") + 12));
            fs >> ft[0] >> ft[1] >> ft[2];
            checkNear(ft[2] + 0.005, 0.176776695 - 0.07, 1e-5, "variant floor drops to the new radius");
        }
    }

    // ================================================================ 3 ====
    // Switches must actually switch things off.
    {
        {
            std::ofstream v("tools/.build/nobonds_scene.json");
            v << "{ \"bonds\": { \"enabled\": false },\n"
                 "  \"module\": { \"physicsEnabled\": false },\n"
                 "  \"floor\": { \"enabled\": false },\n"
                 "  \"output\": { \"proto\": \"tools/.build/NoBonds.proto\",\n"
                 "                \"world\": \"tools/.build/nobonds_world.wbt\",\n"
                 "                \"protoName\": \"NoBonds\" } }\n";
        }
        int rc = runTool("tools/.build/nobonds_scene.json > tools/.build/nobonds.log 2>&1");
        check(rc == 0, "gen_world succeeds with features disabled");
        std::string np = slurp("tools/.build/NoBonds.proto");
        std::string nw = slurp("tools/.build/nobonds_world.wbt");
        check(countOf(np, "Connector {") == 0,        "bonds.enabled=false removes connectors");
        check(!contains(np, "physics Physics {"),     "physicsEnabled=false removes Physics");
        check(!contains(np, "boundingObject"),        "physicsEnabled=false removes boundingObject");
        check(!contains(nw, "ContactProperties"),     "physicsEnabled=false removes ContactProperties");
        check(!contains(nw, "name \"floor\""),        "floor.enabled=false removes the floor");
        check(countOf(nw, "NoBonds {") == 20,         "modules still generated without physics");
    }

    std::cout << "test_gen_world: " << g_pass << " passed, " << g_fail << " failed\n";
    return g_fail == 0 ? 0 : 1;
}
